AllCops:
  Exclude:
    - 'spec/dgit/sources/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.2

ModuleLength:
  Exclude:
    - 'bin/dgit'

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - '*.gemspec'
    - 'spec/**/*.rb'
    - 'bin/dgit'

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 15

Style/Tab:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/ModuleFunction:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/AsciiComments:
  Enabled: false

Style/Copyright:
  Enabled: true
  Notice: '^.*Copyright.*'
