AllCops:
  Exclude:
    - 'spec/dgit/sources/**/*'
    - 'tmp/**/*'
    - 'Vagrantfile'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - 'bin/dgit'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - '*.gemspec'
    - 'spec/**/*.rb'
    - 'bin/dgit'

Metrics/ClassLength:
  Max: 200

Metrics/ParameterLists:
  Max: 15

Layout/Tab:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/ModuleFunction:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/AsciiComments:
  Enabled: false

Style/Copyright:
  Enabled: true
  Notice: '^.*Copyright.*'
