AllCops:
  Exclude:
    - 'spec/dgit/sources/**/*'
    - 'tmp/**/*'
    - 'Vagrantfile'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5
  NewCops: enable

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - 'bin/dgit'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - '*.gemspec'
    - 'spec/**/*.rb'
    - 'bin/dgit'

Metrics/ClassLength:
  Max: 200

Metrics/ParameterLists:
  Max: 15

Layout/IndentationStyle:
  EnforcedStyle: tabs

Layout/IndentationWidth:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Max: 55

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/ModuleFunction:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
    Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/UselessMethodDefinition:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Copyright:
  Enabled: true
  Notice: '^.*Copyright.*'

Style/HashEachMethods:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false