language: ruby
rvm:
- 2.2.0
deploy:
  provider: rubygems
  api_key:
    secure: dp4S2Oyc3w35oLHTYPkb7iBhPr96EcFfQmIobXUbltGaLl2y0nkGmuNauvG8eQUDNGwDtxor/XQWB1uHq1ht4tiaXWTfnVakI1ThUVjjhkKfFciakaxvOyRQ4YCXO4C6/0iemKPEuapSH5FkIL5XRkbCaUbRxTbDy1sax40S7ReFUPMQQVG6tnwD0QvmCINqKzqJzPLtgX9SES8L6Hte3VUsasEbBGDtLzsjO+AfbXV0dd7uUT9PewvSQfnGzPkICTq1O25hgDHnq/67cWkcR2ZuL1kwTgAlskDKt72E/2NdVa1dUIRKID7luCgu16esg7sIPojzn4ATD8D3CILzKTDMus02qAwjaWMX37YSXfih2YJJydbwJ3gpnmQ5h1yfWShlUxhVGUgxS+Jw7hqV/nmHZ6AbU2LCJC/giYAeXvlUb5LEeOnVFYjN1iyOfR7DyMJzqmb/Tt3OS03oekRRtvwwLgYbpk1Lf5qwh+nbstCsQ+k4PctDFSuY+E1URMH0jY4LDcore00y3mN6rpbbycX05c0NY9+tPKnZURfejxgI9JUsMZFu4K0CHzUUfAzQQDVfXSAQ9nqg4LyPRj3outbKhHE6vkvV9ujmSH2Kte2pSugys8ogDlBeBbfHX2oEJ/pYPOQXEZoLhViq+WpowxrzFK+G38yL5jdqjtuTWDI=
